// Generated by CoffeeScript 1.6.3
(function() {
  var consumerApp;

  consumerApp = angular.module("consumerApp", []);

  consumerApp.controller("EventCtrl", function($scope, $http) {
    var base_url, token;
    $scope.uid = "";
    $scope.actorEvents = "";
    token = "e2b0d1626176758db87335875634bbc8";
    base_url = "http://localhost:3024/api/";
    $http({
      method: "GET",
      url: base_url + "events",
      headers: {
        Authorization: "Token token=" + token
      }
    }).success(function(data) {
      return $scope.events = data.events;
    });
    return $scope.findActor = function() {
      var api_url;
      if ($scope.uid !== "") {
        api_url = base_url + "actors/" + $scope.uid + "/events";
        return $http({
          method: "GET",
          url: api_url,
          headers: {
            Authorization: "Token token=" + token
          }
        }).success(function(data) {
          angular.element(document.querySelector("#actor-events-data-area")).css("display", "block");
          return $scope.actorEvents = data.actors;
        }).error(function(status) {
          angular.element(document.querySelector("#actor-events-data-area")).css("display", "none");
          return alert("No actor found with UID " + $scope.uid);
        });
      } else {
        return alert("Please enter valid actor uid");
      }
    };
  });

}).call(this);
